// Prompts for blueprint and HTML generation
// Separated from openai.ts to improve maintainability and prevent file corruption

// ============================================================================
// BLUEPRINT GENERATION PROMPTS
// ============================================================================

export function generateBlueprintPrompt(
  toolName: string,
  niche: string,
  category: string | null,
  goal: string | null
): string {
  return `You are generating clean, professional blueprint content for a premium SaaS dashboard application.

═══════════════════════════════════════════════════════════
CRITICAL UI/UX REQUIREMENTS
═══════════════════════════════════════════════════════════

This blueprint must be:
✓ CLEAN and visually readable inside dashboard cards
✓ CONCISE but valuable (not bloated)
✓ PROFESSIONAL marketing language
✓ SEO-FOCUSED with strategic keywords
✓ FORMATTED for modern SaaS UI sections

DO NOT generate:
✗ Overly long paragraphs
✗ Technical dumps or raw JSON
✗ Broken formatting or serialized objects
✗ Weak one-line filler content
✗ Excessive or repetitive text

Return ONLY pure valid JSON. No markdown fences, no explanations.

Tool Name: ${toolName}
Niche: ${niche}
Category: ${category || "General"}
Goal: ${goal || "Generate traffic"}

Return the complete JSON structure with premium-quality content:`;
}

export function generateRegenerateBlueprintPrompt(
  currentBlueprint: any,
  niche: string,
  goal: string | null
): string {
  return `Regenerate an improved version of this blueprint with fresh variations.

REQUIREMENTS:
- Keep the same tool concept and structure
- Generate NEW variations for purpose, keywords, and monetization
- Maintain professional quality
- Return ONLY valid JSON (no markdown fences)

Current Blueprint:
${JSON.stringify(currentBlueprint, null, 2)}

Niche: ${niche}
Goal: ${goal || "Generate traffic"}

Return the complete improved JSON structure:`;
}

// ============================================================================
// OPTIMIZED HTML GENERATION PROMPTS
// ============================================================================

export function generateOptimizedLandingPagePrompt(blueprint: any): string {
  // Build input fields HTML
  const inputsHTML = Array.isArray(blueprint.inputs_required) && blueprint.inputs_required.length > 0
    ? blueprint.inputs_required.map((input: any, idx: number) => {
        const fieldName = typeof input === 'string' ? input : (input.name || input.label || `Input ${idx + 1}`);
        const fieldType = typeof input === 'object' && input.type === 'select' ? 'select' : 'text';
        
        if (fieldType === 'select') {
          return `
        <div class="tool-field-card">
          <label><span class="tool-icon-chip">AI</span> ${fieldName}</label>
          <div class="tool-select-wrap">
            <select id="input${idx}" required>
              <option value="">Select option</option>
              <option>Option 1</option>
              <option>Option 2</option>
            </select>
          </div>
        </div>`;
        }
        
        return `
        <div class="tool-field-card">
          <label><span class="tool-icon-chip">AI</span> ${fieldName}</label>
          <input type="text" id="input${idx}" placeholder="Enter ${fieldName.toLowerCase()}" required>
        </div>`;
      }).join('\n')
    : `
        <div class="tool-field-card">
          <label><span class="tool-icon-chip">AI</span> Input Value</label>
          <input type="text" id="input0" placeholder="Enter value" required>
        </div>`;

  return `Create a clean, optimized landing page for: ${blueprint.title}

CRITICAL: Output ONLY the complete HTML document. NO markdown fences.

OPTIMIZATION REQUIREMENTS:
- Use reusable CSS classes (NOT repeated inline styles)
- Minimal blur effects (max 2-3 backdrop-filters)
- Simple DOM structure (avoid deep nesting)
- Lightweight gradients (use CSS variables)
- Single shared <style> block
- Total HTML size under 50KB
- The .tool-card section must be a premium AI SaaS tool UI, not a raw/default form.
- Tool inputs/selects/buttons/results must use custom classes: tool-header, tool-ai-badge, tool-progress, tool-form-grid, tool-field-card, tool-select-wrap, tool-primary-button, tool-result-dashboard, tool-score-card, tool-insight-card, tool-recommendation-card, tool-monetization-card.
- Do not include cheap autogenerated footer text like "© 2023".

TEMPLATE STRUCTURE:

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${blueprint.seo_title || blueprint.title}</title>
  <meta name="description" content="${blueprint.seo_description || blueprint.description || blueprint.purpose}">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    :root {
      --primary: #6E57E0;
      --primary-dark: #5B48E0;
      --gradient: linear-gradient(135deg, #6E57E0, #A78BFA);
      --text: #1A1E2B;
      --text-light: #4B5565;
      --bg: #ffffff;
      --border: #E9EDF4;
      --shadow: 0 15px 30px -10px rgba(0,0,0,0.1);
    }
    
    body {
      font-family: 'Inter', sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
    }
    
    .container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }
    
    /* Hero */
    .hero {
      padding: 100px 0 80px;
      text-align: center;
      background: radial-gradient(ellipse at top, rgba(110,87,224,0.04), transparent 70%);
    }
    .hero h1 {
      font-size: clamp(36px, 6vw, 64px);
      font-weight: 800;
      margin-bottom: 20px;
      letter-spacing: -0.02em;
    }
    .hero .gradient { background: var(--gradient); -webkit-background-clip: text; background-clip: text; color: transparent; }
    .hero p { font-size: 18px; color: var(--text-light); max-width: 600px; margin: 0 auto 32px; }
    
    /* Buttons */
    .btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 14px 28px;
      border-radius: 12px;
      font-weight: 600;
      text-decoration: none;
      transition: all 0.2s;
      cursor: pointer;
      border: none;
      font-family: inherit;
      font-size: 16px;
    }
    .btn-primary {
      background: var(--gradient);
      color: white;
      box-shadow: 0 8px 20px -6px rgba(110,87,224,0.3);
    }
    .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 12px 24px -8px rgba(110,87,224,0.4); }
    .btn-outline {
      background: transparent;
      border: 1.5px solid var(--border);
      color: var(--text);
    }
    .btn-outline:hover { border-color: var(--primary); background: rgba(110,87,224,0.04); }
    
    /* Premium Embedded Tool System */
    .tool-card {
      position: relative;
      overflow: hidden;
      background:
        radial-gradient(circle at 10% 0%, rgba(110,87,224,0.14), transparent 34%),
        linear-gradient(180deg, rgba(255,255,255,0.95), rgba(248,250,255,0.92));
      border-radius: 36px;
      padding: clamp(24px, 4vw, 42px);
      margin: 40px 0;
      border: 1px solid rgba(226,232,240,0.95);
      box-shadow: 0 30px 80px rgba(15,23,42,0.10);
    }
    .tool-header { text-align: center; max-width: 780px; margin: 0 auto 28px; }
    .tool-ai-badge { display: inline-flex; align-items: center; gap: 8px; border: 1px solid #e8e5ff; background: rgba(110,87,224,0.08); color: var(--primary); border-radius: 999px; padding: 8px 12px; font-size: 11px; font-weight: 800; letter-spacing: .14em; text-transform: uppercase; margin-bottom: 14px; }
    .tool-card h2 { font-size: clamp(28px, 4vw, 40px); line-height: 1.05; margin-bottom: 10px; text-align: center; letter-spacing: -0.03em; }
    .tool-card > p, .tool-header p { text-align: center; color: var(--text-light); margin-bottom: 0; font-size: 16px; }
    .tool-progress { height: 8px; max-width: 440px; margin: 0 auto 26px; border-radius: 999px; background: #eef2ff; overflow: hidden; }
    .tool-progress span { display: block; width: 74%; height: 100%; border-radius: inherit; background: var(--gradient); }
    
    .tool-form { padding: clamp(18px, 3vw, 28px); border: 1px solid var(--border); border-radius: 28px; background: rgba(255,255,255,0.78); box-shadow: 0 18px 42px rgba(15,23,42,0.06); }
    .tool-form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; margin-bottom: 18px; }
    .tool-field-card { display: flex; flex-direction: column; gap: 8px; padding: 14px; border-radius: 22px; background: #fff; border: 1px solid var(--border); box-shadow: 0 12px 26px rgba(15,23,42,0.04); }
    .tool-field-card label {
      font-weight: 800;
      font-size: 11px;
      color: var(--text);
      display: flex;
      align-items: center;
      gap: 8px;
      letter-spacing: .09em;
      text-transform: uppercase;
    }
    .tool-icon-chip { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; border-radius: 11px; background: rgba(110,87,224,0.10); color: var(--primary); font-size: 10px; font-weight: 900; letter-spacing: 0; }
    .tool-select-wrap { position: relative; }
    .tool-select-wrap::after { content: ""; position: absolute; right: 16px; top: 50%; width: 8px; height: 8px; border-right: 2px solid var(--primary); border-bottom: 2px solid var(--primary); transform: translateY(-65%) rotate(45deg); pointer-events: none; }
    input, select {
      width: 100%;
      padding: 14px 16px;
      border: 1.5px solid var(--border);
      border-radius: 18px;
      font-family: inherit;
      font-size: 15px;
      font-weight: 600;
      transition: all 0.2s;
      background: #F8FAFF;
      color: var(--text);
    }
    select {
      appearance: none;
      padding-right: 44px;
    }
    input:focus, select:focus {
      outline: none;
      border-color: var(--primary);
      background: white;
      box-shadow: 0 0 0 4px rgba(110,87,224,0.14), 0 14px 30px rgba(15,23,42,0.08);
    }
    
    .tool-primary-button {
      width: 100%;
      padding: 16px;
      background: linear-gradient(135deg, var(--primary), #111827);
      color: white;
      border: none;
      border-radius: 18px;
      font-weight: 800;
      font-size: 15px;
      cursor: pointer;
      transition: all 0.2s;
      margin-top: 8px;
      box-shadow: 0 18px 34px rgba(110,87,224,0.26);
    }
    .tool-primary-button:hover { transform: translateY(-2px); box-shadow: 0 24px 44px rgba(110,87,224,0.34); }
    
    .tool-result-dashboard {
      margin-top: 32px;
      background: linear-gradient(180deg, #fff, #F8FAFF);
      border-radius: 28px;
      padding: clamp(20px, 3vw, 28px);
      border: 1px solid rgba(110,87,224,0.18);
      display: none;
      box-shadow: 0 24px 52px rgba(15,23,42,0.08);
    }
    .tool-result-dashboard.show { display: block; }
    .tool-result-dashboard h3 { margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }
    .tool-score-card, .tool-insight-card, .tool-recommendation-card, .tool-monetization-card { border: 1px solid var(--border); border-radius: 20px; padding: 18px; background: #fff; margin-top: 12px; }
    
    /* Grid Sections */
    .grid-3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 24px; margin: 40px 0; }
    .card {
      background: white;
      border-radius: 20px;
      padding: 28px;
      border: 1px solid var(--border);
      transition: transform 0.2s;
    }
    .card:hover { transform: translateY(-4px); }
    .card-icon {
      width: 48px;
      height: 48px;
      background: linear-gradient(135deg, #F5F3FF, #FFF);
      border-radius: 16px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 24px;
      color: var(--primary);
      margin-bottom: 16px;
      border: 1px solid #E8E5FF;
    }
    .card h3 { font-size: 18px; margin-bottom: 8px; }
    .card p { color: var(--text-light); font-size: 15px; }
    
    /* FAQ */
    .faq { max-width: 800px; margin: 40px auto; }
    details {
      background: white;
      border: 1px solid var(--border);
      border-radius: 16px;
      margin-bottom: 12px;
      padding: 20px 24px;
    }
    summary {
      font-weight: 700;
      cursor: pointer;
      list-style: none;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    summary::-webkit-details-marker { display: none; }
    summary::after { content: '+'; font-size: 24px; color: var(--primary); }
    details[open] summary::after { content: '−'; }
    .faq-answer { margin-top: 12px; padding-top: 12px; border-top: 1px solid var(--border); color: var(--text-light); }
    
    /* CTA */
    .cta {
      background: linear-gradient(135deg, #1E2330, #2C3548);
      border-radius: 32px;
      padding: 48px 32px;
      text-align: center;
      color: white;
      margin: 60px 0;
    }
    .cta h3 { font-size: 32px; margin-bottom: 12px; }
    .cta p { color: rgba(255,255,255,0.8); margin-bottom: 24px; }
    
    /* Footer */
    footer { text-align: center; padding: 40px 24px; color: var(--text-light); font-size: 14px; border-top: 1px solid var(--border); }
    
    /* Mobile */
    @media (max-width: 768px) {
      .hero { padding: 60px 0 40px; }
      .tool-card { padding: 18px; border-radius: 26px; }
      .tool-form-grid { grid-template-columns: 1fr; }
    }
  </style>
</head>
<body>

<!-- Hero -->
<section class="hero">
  <div class="container">
    <h1>${blueprint.title.split(' ').slice(0, -1).join(' ')} <span class="gradient">${blueprint.title.split(' ').slice(-1)[0]}</span></h1>
    <p>${blueprint.purpose}</p>
    <div style="display: flex; gap: 12px; justify-content: center; flex-wrap: wrap;">
      <a href="#tool" class="btn btn-primary"><i class="fas fa-calculator"></i> ${blueprint.cta_text || 'Get Started'}</a>
      <a href="#how" class="btn btn-outline"><i class="fas fa-play-circle"></i> How it works</a>
    </div>
  </div>
</section>

<!-- Tool -->
<div class="container" id="tool">
  <div class="tool-card">
    <div class="tool-header">
      <div class="tool-ai-badge">AI business intelligence</div>
      <h2>${blueprint.title}</h2>
      <p>${blueprint.description || blueprint.purpose}</p>
    </div>
    <div class="tool-progress"><span></span></div>
    <form id="form" class="tool-form" onsubmit="event.preventDefault(); calculate();">
      <div class="tool-form-grid">
        ${inputsHTML}
      </div>
      <button type="submit" class="tool-primary-button">
        ${blueprint.cta_text || 'Reveal My Opportunity'}
      </button>
    </form>
    <div id="results" class="tool-result-dashboard">
      <h3>Your AI Opportunity Report</h3>
      <div class="tool-score-card"><strong>Opportunity score:</strong> Ready to analyze</div>
      <div id="resultsContent"></div>
    </div>
  </div>
</div>

<!-- How It Works -->
<section id="how" class="container">
  <h2 style="text-align: center; font-size: 32px; margin-bottom: 32px;">How It Works</h2>
  <div class="grid-3">
    <div class="card">
      <div class="card-icon">1</div>
      <h3>Enter Your Data</h3>
      <p>Fill in the form fields with your information</p>
    </div>
    <div class="card">
      <div class="card-icon">2</div>
      <h3>Get Results</h3>
      <p>Our algorithm calculates your personalized results instantly</p>
    </div>
    <div class="card">
      <div class="card-icon">3</div>
      <h3>Take Action</h3>
      <p>Use the insights to make informed decisions</p>
    </div>
  </div>
</section>

<!-- Benefits -->
<section class="container">
  <h2 style="text-align: center; font-size: 32px; margin-bottom: 32px;">Key Benefits</h2>
  <div class="grid-3">
    ${Array.isArray(blueprint.features) && blueprint.features.length > 0
      ? blueprint.features.slice(0, 6).map((f: any, i: number) => {
          const icons = ['bolt', 'chart-line', 'shield-alt', 'clock', 'users', 'check-circle'];
          const title = typeof f === 'string' ? f : (f.title || f.name || `Benefit ${i + 1}`);
          const desc = typeof f === 'object' && f.description ? f.description : 'Powerful feature to help you succeed';
          return `
    <div class="card">
      <div class="card-icon"><i class="fas fa-${icons[i % icons.length]}"></i></div>
      <h3>${title}</h3>
      <p>${desc}</p>
    </div>`;
        }).join('\n')
      : `
    <div class="card">
      <div class="card-icon"><i class="fas fa-bolt"></i></div>
      <h3>Fast & Accurate</h3>
      <p>Get instant, reliable results every time</p>
    </div>
    <div class="card">
      <div class="card-icon"><i class="fas fa-shield-alt"></i></div>
      <h3>Secure & Private</h3>
      <p>Your data stays private and secure</p>
    </div>
    <div class="card">
      <div class="card-icon"><i class="fas fa-check-circle"></i></div>
      <h3>Easy to Use</h3>
      <p>Simple interface, powerful results</p>
    </div>`}
  </div>
</section>

<!-- FAQ -->
<section class="container">
  <h2 style="text-align: center; font-size: 32px; margin-bottom: 32px;">Frequently Asked Questions</h2>
  <div class="faq">
    <details>
      <summary>How does this tool work?</summary>
      <div class="faq-answer">This tool uses advanced calculations based on ${blueprint.category || 'your input data'} to provide accurate results instantly.</div>
    </details>
    <details>
      <summary>Is it free to use?</summary>
      <div class="faq-answer">Yes, this tool is completely free with no sign-up required.</div>
    </details>
    <details>
      <summary>How accurate are the results?</summary>
      <div class="faq-answer">Our algorithm provides highly accurate results based on industry-standard calculations and real-time data.</div>
    </details>
    <details>
      <summary>Do I need to create an account?</summary>
      <div class="faq-answer">No account needed. Simply enter your data and get instant results.</div>
    </details>
  </div>
</section>

<!-- CTA -->
<div class="container">
  <div class="cta">
    <h3>${blueprint.cta_text || 'Ready to Get Started?'}</h3>
    <p>Join thousands using this tool every day</p>
    <a href="#tool" class="btn btn-primary">Get Started Now</a>
  </div>
</div>

<!-- Footer -->
<footer>
  <p>${blueprint.title} · AI business opportunity intelligence for modern growth teams</p>
</footer>

<script>
function calculate() {
  const results = document.getElementById('results');
  const content = document.getElementById('resultsContent');
  
  // Get input values
  const inputs = document.querySelectorAll('#form input, #form select');
  const values = Array.from(inputs).map(i => (i as HTMLInputElement).value);
  
  // Implement calculation logic from blueprint
  // ${blueprint.calculation_logic || 'const result = values.reduce((a, b) => Number(a) + Number(b), 0);'}
  
  // Display premium AI report blocks
  content.innerHTML = '<div class="tool-insight-card"><strong>Strategic insight:</strong> Your inputs reveal a focused business opportunity worth prioritizing.</div><div class="tool-recommendation-card"><strong>Next move:</strong> Build the highest-intent traffic path first, then route visitors into a clear conversion offer.</div><div class="tool-monetization-card"><strong>Monetization path:</strong> Use this result to support lead capture, consultation offers, affiliate recommendations, or a premium digital product funnel.</div>';
  results.classList.add('show');
  results.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

// Smooth scroll
document.querySelectorAll('a[href^="#"]').forEach(a => {
  a.addEventListener('click', e => {
    const target = document.querySelector(a.getAttribute('href') || '');
    if (target) {
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});
</script>
</body>
</html>

OUTPUT THE COMPLETE HTML NOW (no markdown, no explanations):`;
}

export function generateOptimizedToolHTMLPrompt(blueprint: any, action: 'standalone' | 'embed'): string {
  const isEmbed = action === 'embed';
  
  if (isEmbed) {
    return `Create a premium embeddable AI business tool widget for: ${blueprint.title}

CRITICAL RULES:
- NO <!DOCTYPE>, <html>, <head>, or <body> tags
- NO full document structure
- Output ONLY the tool content in a single wrapper div
- NO markdown fences
- Use reusable scoped CSS classes, not repeated inline styles
- Total output under 45KB
- The widget must feel like a mini SaaS application, not a generic calculator embed

REQUIRED COMPONENTS:
- wrapper class: taf-widget
- header: taf-widget-header with taf-ai-badge
- progress/steps: taf-stepper and taf-progress
- form: taf-tool-panel with taf-field-card for every input
- selects: taf-select-wrap around every select
- CTA: taf-primary-button with premium gradient styling
- results: taf-insight-dashboard with taf-score-meter, taf-metric-card, taf-strategy-card, taf-cta-block

DESIGN RULES:
- Use Inter/Manrope typography, 20px+ radius, soft borders, glass-light surfaces, layered shadows, premium muted gradients
- Inputs must have custom focus glow and must not look browser-default
- Results must be an AI opportunity report with traffic, conversion, monetization, and next action cards
- No footer inside embed mode
- No Font Awesome, Bootstrap, Tailwind CDN, external icon CDN, or old calculator wording unless the blueprint requires it

BLUEPRINT:
${JSON.stringify(blueprint, null, 2)}

Generate the complete premium embed code now (wrapper div only):`;
  }
  
  // Standalone version
  return `Create a premium standalone AI SaaS product page for: ${blueprint.title}

OUTPUT RULES:
- Output ONLY raw HTML. No markdown fences or explanations.
- Use a complete <!DOCTYPE html> document with html, head, body.
- Use Inter or Manrope from Google Fonts.
- Use one reusable <style> block and one small <script> block.
- Avoid repeated inline styles, Font Awesome, Bootstrap, Tailwind CDN, icon CDNs, external images, and invalid CSS like darken().
- Use premium token names like --brand-primary, --brand-secondary, --surface, --ink, --muted, and --line.

DESIGN DIRECTION:
- This must feel like a funded modern AI startup product, not a generated landing page template.
- Visual quality should feel close to Linear, Stripe, Framer, Raycast, Arc Browser, Notion AI, and Vercel.
- Use soft neutral backgrounds, layered gradients, glass-light surfaces, large radius, refined shadows, elegant borders, and precise spacing rhythm.
- Do not create generic bright gradient heroes, flat white card grids, fake SaaS dashboards, old startup sections, or Bootstrap-style rows.

REQUIRED COMPONENT CLASSES:
- experience-shell: main page wrapper with layered visual atmosphere.
- site-nav: minimal premium navigation.
- hero-grid: split cinematic hero.
- hero-composition: right-side product composition.
- ai-product-preview: qualitative AI analysis UI, not fake numbers.
- trust-bar: proof row without fabricated metrics.
- tool-panel: premium interactive product area.
- configurator-card: app-like AI configurator.
- field-card: custom grouped inputs/selects.
- analysis-workspace: hidden paid-report style results dashboard.
- score-ring or score-meter: visual opportunity score.
- signal-card: traffic, conversion, authority, or monetization insight blocks.
- strategy-card: actionable AI recommendations.
- monetization-card: realistic revenue path cards.
- timeline-rail: modern process or strategy timeline.
- faq-section: polished FAQ.
- site-footer and footer-grid: minimal premium SaaS footer.

TOOL EXPERIENCE:
- Use a literal <form id="business-asset-form"> with all blueprint inputs.
- Inputs/selects must look custom and premium, with focus states and grouped labels.
- Submit CTA should say something like "Reveal My Opportunity", "Generate My Strategy", or "Build My Revenue Plan".
- Results must be an AI insight workspace with opportunity score, signal cards, strategy cards, monetization cards, and next steps.

CONTENT RULES:
- Avoid generic phrases like "Powerful Features", "Why Choose Us", "Get Started Today", and "Calculate Now".
- Do not invent fake vanity metrics such as "Traffic 120k", "Revenue 500k", "$500k", or similar fabricated proof.
- Copy should focus on revenue growth, traffic intelligence, lead capture, monetization, authority, and conversion momentum.

BLUEPRINT:
${JSON.stringify(blueprint, null, 2)}

Generate the complete premium standalone HTML now:`;
}

function generateInputFields(inputs: any[]): string {
  if (!Array.isArray(inputs) || inputs.length === 0) {
    return `
      <div style="display:flex;flex-direction:column;gap:8px;">
        <label style="font-weight:600;font-size:14px;color:#2C3A58;">Input Value</label>
        <input type="text" required style="padding:12px 16px;border:1.5px solid #E9EDF4;border-radius:12px;font-size:15px;background:#F9FAFE;">
      </div>`;
  }
  
  return inputs.map((input, idx) => {
    const fieldName = typeof input === 'string' ? input : (input.name || input.label || `Input ${idx + 1}`);
    const fieldType = typeof input === 'object' && input.type === 'select' ? 'select' : 'text';
    
    if (fieldType === 'select') {
      return `
      <div style="display:flex;flex-direction:column;gap:8px;">
        <label style="font-weight:600;font-size:14px;color:#2C3A58;">${fieldName}</label>
        <select id="input${idx}" required style="padding:12px 16px;border:1.5px solid #E9EDF4;border-radius:12px;font-size:15px;background:#F9FAFE;">
          <option value="">Select</option>
          <option>Option 1</option>
          <option>Option 2</option>
        </select>
      </div>`;
    }
    
    return `
      <div style="display:flex;flex-direction:column;gap:8px;">
        <label style="font-weight:600;font-size:14px;color:#2C3A58;">${fieldName}</label>
        <input type="text" id="input${idx}" placeholder="Enter ${fieldName.toLowerCase()}" required style="padding:12px 16px;border:1.5px solid #E9EDF4;border-radius:12px;font-size:15px;background:#F9FAFE;">
      </div>`;
  }).join('\n');
}
